project(
    'hw_saturation',
    'cpp',
    version: '1.0.0',
    default_options: [
        'cpp_std=c++17',
        'warning_level=3',
    ],
)

wayfire = dependency(
    'wayfire',
    version: '>=0.11.0',
)

libdrm = dependency(
    'libdrm',
    version: '>=2.4.120',
)

subdir('src')
subdir('metadata')
